Bump go, controller-runtime and flux components versions
fluxcd/source-watcher pull request #25
Opened 2022-01-12 18:57 UTC by aryan9600

Signed-off-by: Sanskar Jaiswal <sanskar.jaiswal@weave.works>

2022-01-12 20:01 UTC, relu requested changes

2022-01-12 20:01 UTC, relu commented on controllers/gitrepository_watcher.go
> +	}
Can you please change this to `log := ctrl.LoggerFrom(ctx)`?

2022-01-12 20:07 UTC, relu requested changes
Please also:
- [ ] Update the `controller-gen` tool to `0.7.0` in the [Makefile](https://github.com/fluxcd/source-watcher/blob/main/Makefile#L74)
- [ ] Update the [Dockerfile](https://github.com/fluxcd/source-watcher/blob/main/Dockerfile#L1) base image go version
- [ ] Update the [Dockerfile](https://github.com/fluxcd/source-watcher/blob/main/Dockerfile#L19) alpine version to 3.15
- [ ] Update the GitHub Actions [test workflow file](https://github.com/fluxcd/source-watcher/blob/main/.github/workflows/test.yaml#L25) go-version

Thank you for your contribution!

2022-01-13 10:23 UTC, stefanprodan commented
Please rebase with main, I've merged your Makefile changes.

2022-01-13 10:53 UTC, stefanprodan approved these changes
LGTM

Thanks @aryan9600 for the updates and thanks @relu for guidance

2022-01-13 10:54 UTC, merged